server:
  port: 8081

spring:
  application:
    name: auth-service

  main:
    allow-bean-definition-overriding: true

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  security:
    otp:
      confirmation: 5
      completion: 15
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/my-finance

keycloak:
  client-id: auth-service
  client-secret: E5jc2zxsL39qCMMnRQhjMfpqeAZsavSI