server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service

  main:
    allow-bean-definition-overriding: true

  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  security:
    otp:
      confirmation: 5
      completion: 15
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8762/realms/my-finance}

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:auth-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:E5jc2zxsL39qCMMnRQhjMfpqeAZsavSI}