server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  security:
    otp:
      confirmation: 5
      completion: 15
    jwt:
      expiration: 1
      secret: VeryStrangeSecretForJWTHS512SignatureAlgorithm64ByteLength
