version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0
    command: [start-dev, --http-port=8762]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - localhost
    ports:
      - '8762:8762'
      - '8787:8787'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  localhost:
    driver: bridge