server:
  port: 8080

spring:
  application:
    name: account-service

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      expiration: 1
      secret: VeryStrangeSecretForJWTHS512SignatureAlgorithm64ByteLength
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8762/realms/my-finance
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

